#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
wname L3GD &

bspc monitor -d   勇 ﱮ     

bspc config border_width         2
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill /home/roma/Imágenes/Font/Font.jpeg
~/.config/polybar/./launch.sh
bspc config focus_follows_pointer true

bspc config border_with false
picom --experimental-backend &
